<?php

namespace App\Services;

class SalesReportPdf
{
    /**
     * @param array{
     *     title: string,
     *     starts_at: string,
     *     ends_at: string,
     *     summary: array{
     *         revenue: float,
     *         purchase_total: float,
     *         expenses: float,
     *         profit: float,
     *         sold_count: int,
     *         margin_percent: float|null
     *     },
     *     rows: array<int, array{
     *         title: string,
     *         sold_at: string,
     *         sale_price: float,
     *         purchase_price: float,
     *         expenses: float,
     *         profit: float,
     *         margin_percent: float|null
     *     }>
     * } $report
     */
    public function make(array $report): string
    {
        $pages = [];
        $rows = array_chunk($report['rows'], 24);

        if ($rows === []) {
            $rows = [[]];
        }

        foreach ($rows as $pageIndex => $pageRows) {
            $pages[] = $this->page($report, $pageRows, $pageIndex + 1, count($rows));
        }

        return $this->document($pages);
    }

    /**
     * @param array<int, array<string, mixed>> $rows
     */
    private function page(array $report, array $rows, int $page, int $pageCount): string
    {
        $content = '';
        $content .= $this->text(40, 800, 20, 'AutoMarsi Sales Report');
        $content .= $this->text(40, 778, 10, "{$report['title']} | {$report['starts_at']} to {$report['ends_at']}");
        $content .= $this->text(40, 748, 11, 'Revenue: '.$this->money($report['summary']['revenue']));
        $content .= $this->text(180, 748, 11, 'Purchase: '.$this->money($report['summary']['purchase_total']));
        $content .= $this->text(330, 748, 11, 'Expenses: '.$this->money($report['summary']['expenses']));
        $content .= $this->text(40, 728, 11, 'Profit: '.$this->money($report['summary']['profit']));
        $content .= $this->text(180, 728, 11, 'Margin: '.$this->percent($report['summary']['margin_percent']));
        $content .= $this->text(330, 728, 11, 'Sold cars: '.$report['summary']['sold_count']);

        $content .= $this->text(40, 688, 9, 'Date');
        $content .= $this->text(100, 688, 9, 'Vehicle');
        $content .= $this->text(282, 688, 9, 'Sale');
        $content .= $this->text(352, 688, 9, 'Purchase');
        $content .= $this->text(432, 688, 9, 'Expenses');
        $content .= $this->text(512, 688, 9, 'Profit');
        $content .= $this->line(40, 680, 555, 680);

        $y = 660;

        if ($rows === []) {
            $content .= $this->text(40, $y, 10, 'No sold vehicles found for this period.');
        }

        foreach ($rows as $row) {
            $content .= $this->text(40, $y, 8, (string) $row['sold_at']);
            $content .= $this->text(100, $y, 8, $this->clip((string) $row['title'], 34));
            $content .= $this->text(282, $y, 8, $this->money((float) $row['sale_price']));
            $content .= $this->text(352, $y, 8, $this->money((float) $row['purchase_price']));
            $content .= $this->text(432, $y, 8, $this->money((float) $row['expenses']));
            $content .= $this->text(512, $y, 8, $this->money((float) $row['profit']));
            $y -= 22;
        }

        $content .= $this->text(40, 38, 8, "Generated by AutoMarsi admin | Page {$page} of {$pageCount}");

        return $content;
    }

    /**
     * @param array<int, string> $pages
     */
    private function document(array $pages): string
    {
        $pageCount = count($pages);
        $fontObject = 3 + ($pageCount * 2);
        $objects = [
            1 => '<< /Type /Catalog /Pages 2 0 R >>',
            2 => '<< /Type /Pages /Kids ['.collect(range(0, $pageCount - 1))
                ->map(fn (int $index) => (3 + ($index * 2)).' 0 R')
                ->implode(' ').'] /Count '.$pageCount.' >>',
        ];

        foreach ($pages as $index => $content) {
            $pageObject = 3 + ($index * 2);
            $contentObject = $pageObject + 1;

            $objects[$pageObject] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 {$fontObject} 0 R >> >> /Contents {$contentObject} 0 R >>";
            $objects[$contentObject] = "<< /Length ".strlen($content)." >>\nstream\n{$content}endstream";
        }

        $objects[$fontObject] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
        ksort($objects);

        $pdf = "%PDF-1.4\n";
        $offsets = [0 => 0];

        foreach ($objects as $number => $object) {
            $offsets[$number] = strlen($pdf);
            $pdf .= "{$number} 0 obj\n{$object}\nendobj\n";
        }

        $xref = strlen($pdf);
        $pdf .= "xref\n0 ".(count($objects) + 1)."\n";
        $pdf .= "0000000000 65535 f \n";

        foreach (array_keys($objects) as $number) {
            $pdf .= sprintf("%010d 00000 n \n", $offsets[$number]);
        }

        $pdf .= "trailer\n<< /Size ".(count($objects) + 1)." /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xref}\n%%EOF";

        return $pdf;
    }

    private function text(float $x, float $y, int $size, string $text): string
    {
        return "BT /F1 {$size} Tf {$x} {$y} Td (".$this->escape($text).") Tj ET\n";
    }

    private function line(float $x1, float $y1, float $x2, float $y2): string
    {
        return "{$x1} {$y1} m {$x2} {$y2} l S\n";
    }

    private function escape(string $text): string
    {
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
    }

    private function clip(string $text, int $length): string
    {
        return mb_strlen($text) > $length
            ? mb_substr($text, 0, $length - 3).'...'
            : $text;
    }

    private function money(float $value): string
    {
        return 'EUR '.number_format($value, 0, '.', ',');
    }

    private function percent(float|null $value): string
    {
        return $value === null ? '-' : number_format($value, 2).'%';
    }
}
